### ISSUE TITLE
The logged trace number doesn't match the valid trace number

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#66]
Example:
> Matched sample count does not equal to gathered sample count. Expected: 6, Actual: 3 \
... \
Service Profiler session finished. Samples: 6

Expected output for the samples: 3.
Actual output for the samples: 6.

**Comment by SidShetye** [comment]
We're seeing this issue. If it helps, there are a few other AI related log entries right around this

```
2019-12-11 00:02:21.288 +00:00 [Warning] ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator: All activities are not found in the trace. First one: Start/#29/1/52/1/.

2019-12-11 00:02:21.290 +00:00 [Warning] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: Matched sample count does not equal to gathered sample count. Expected: 5, Actual: 3

2019-12-11 00:14:20.905 +00:00 [Error] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider:
Expected trace validation error.
ServiceProfiler.EventPipe.Client.TraceValidators.ValidateFailedException: [ActivityListValidator] No sample activity matches the trace.
   at ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator.ValidateImp(IEnumerable`1 samples)
   at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
   at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e)

2019-12-11 00:14:27.177 +00:00 [Warning] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider:
Trace validation failed. No customer events released.
```

This is on Azure App Service (Linux Containers), ASP.NET Core 3.1 and `<PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.0.0-beta4" />`

**Comment by SidShetye** [comment]
@xiaomi7732 : What is the impact of those warnings and errors? This is in our production application, so if we're missing a few traces, that's ok for now but if it's a bit more serious, we would like to disable AI till this is resolved. Thanks

**Comment by xiaomi7732** [comment]
Hi @SidShetye , thank you for noticing the logs and report it back. Depends on the running environment, these warnings could happen more or less frequent.

The impact for the warnings is actually pretty minor - it just give us some insights that mismatch is happening.
The impact for the error is that a trace gathered will be dropped and you might not having the trace for analysis.

Neither should impact the execution of your application.

**Comment by xiaomi7732** [comment]
Fixed in [2.0.0-beta5](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.0.0-beta5).

**Comment by SidShetye** [comment]
What is the testing/Q&A process behind the releases here? Because we're still seeing 

```
2019-12-24 02:43:52.598 +00:00 [Warning] ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator: 
All activities are not found in the trace. First one: Stop/#26/1/99/. 
------------------------------ 
2019-12-24 02:43:52.598 +00:00 [Warning] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: 
Matched sample count does not equal to gathered sample count. Expected: 22, Actual: 10
--
```

This is happening much more frequently in `beta5`.

**Comment by SidShetye** [comment]
Also, is there a way to mute app insight logs? @davidfowl - any ideas?

Our equivalent configuration is shown below. We have a custom logger that pages our admins on any warnings but given the way ASP.NET Core logging works ([here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration) `If levels are specified in Logging.{providername}.LogLevel, they override anything set in Logging.LogLevel`), we cannot mute and are getting too many phantom alerts. We don't want to disable system level logs nor ruin anyone's holidays by constantly bombarding them with russian roulet alerts, so some quick tips would help.

```
<snip>
"logging": {
    "instantPageAdmin": {
      "logLevel": {
        "default": "warning"
      }
    },
    "logLevel": {
      "default": "warning",
      "microsoft": "warning",
      "microsoft.hosting.lifetime": "information",
      "ServiceProfiler.EventPipe.Client": "none"
    }
  },
<snip>
```

**Comment by SidShetye** [comment]
Also seeing this in the logs
```
2019-12-24 03:16:37.209 +00:00 [Error] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: 
Expected trace validation error. ServiceProfiler.EventPipe.Client.TraceValidators.ValidateFailedException: [ActivityListValidator] No sample activity matches the trace.
    at ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator.ValidateImp(IEnumerable`1 samples)
    at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
    at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
    at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.ValidateSamples(String traceFilePath, List`1 samples) 
------------------------------ 
2019-12-24 03:16:37.252 +00:00 [Warning] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: 
Trace validation failed. Upload aborted and no customer events released.
--
```

**Comment by xiaomi7732** [comment]
@Sid thanks for your feedback. The warnings are there for debugging purpose. We'll look into lower the level.

As for now, to mute Profiler logs, try the following settings:
```jsonc
<snip>
"logging": {
    "instantPageAdmin": {
      "logLevel": {
        "default": "warning",
        // Append the following configuration
        "ServiceProfiler.EventPipe.Client": "none"
      }
    },
    "logLevel": {
      "default": "warning",
      "microsoft": "warning",
      "microsoft.hosting.lifetime": "information",
      // Keep this one
      "ServiceProfiler.EventPipe.Client": "none"
    }
  },
<snip>
```

**Comment by khowling** [comment]
> Also seeing this in the logs
> 
> ```
> 2019-12-24 03:16:37.209 +00:00 [Error] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: 
> Expected trace validation error. ServiceProfiler.EventPipe.Client.TraceValidators.ValidateFailedException: [ActivityListValidator] No sample activity matches the trace.
>     at ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator.ValidateImp(IEnumerable`1 samples)
>     at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
>     at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
>     at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.ValidateSamples(String traceFilePath, List`1 samples) 
> ------------------------------ 
> 2019-12-24 03:16:37.252 +00:00 [Warning] ServiceProfiler.EventPipe.Client.ServiceProfilerProvider: 
> Trace validation failed. Upload aborted and no customer events released.
> --
> ```

I have the same issue, with a very small .NET Core 3 app.  Did you get any resolution to this?
